### ISSUE TITLE
EuIrcBot still OOMs a lot

### ISSUE THREAD

**Issue by LinuxMercedes** [euank/ek8s#1]
According to [something I saw on the internet](https://blog.risingstack.com/finding-a-memory-leak-in-node-js/), node by default aims to eat about 1.5 GB. You can fix this with the command-line flag `--max_old_space_size=N`, where N is the number of megabytes of RAM you (approximately) want it to consume.

I'm currently testing with 200 MB allocated for this, and it just quit with `Probably lost connection, terminating process.` I'll fiddle some more and see what happens.

**Comment by euank** [comment]
I vote for rewriting in something that isn't JS.

In the meanwhile, I bumped the memory numbers in commit 63bf7635be78fa1dd5cfc20178a55f71399c440b

If you want to repro in an environment closer to this, you can try with `docker run --memory=xxxM`. That's the equiv of the 'limit' field.

**Comment by LinuxMercedes** [comment]
OK, so even if this isn't the issue at hand, I still vote for setting that flag since I did have OOM problems with euircbot on a t2.nano (512 MB RAM). 100 seemed to work fine for me?

**Comment by euank** [comment]
No OOMs since said bump, and the original issue was a bit of a mis-diagnosis.

Closing.

**Comment by euank** [comment]
Remembered that this is also recommending a flag, reopened for adding the flag

**Comment by euank** [comment]
This was fixed by https://github.com/euank/EuIrcBot/pull/136

```
$ kubectl exec -it euircbot-3528955448-s0783 ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
bot          1  0.0  5.9 1299472 121280 ?      Ssl  Mar05   0:51 node --max_old_space_size=150 bot.js
```
